Don't link an app to a repo
If we link an app to a repo, we can't reliably deploy the same image to
different apps.

If we search for an app first based on repo the following bug occurs:

    $ emp create my-app
    $ emp deploy -a my-app remind101/acme-inc
    $ emp releases -a my-app
    v1    Jul 29 19:16  Deploy remind101/acme-inc:latest

    # we've correcly released remind101/acme-inc to my-app. deploying
    # "remind101/acme-inc" without specifying an app, should create an
    # "acme-inc" app as the default.

    $ emp deploy remind101/acme-inc
    $ emp releases -a acme-inc
    error: Request failed, the specified resource does not exist
    $ emp releases -a my-app
    v1    Jul 29 19:17  Deploy remind101/acme-inc:latest
    v2    Jul 29 19:17  Deploy remind101/acme-inc:latest

    # "acme-inc" is never created because "AppsFindOrCreateByRepo"
    # returns the first app associated with that image.

By searching for apps only by name, including the default
"AppNameFromRepo", you avoid the above bug while maintaining the same
behavior.